#ifndef FUNCTION_CHECK_H
#define FUNCTION_CHECK_H
#include <QString>
int CheckcmbModulation_1(QString);
int CheckcmbModulation_2(QString);
int Check_Scamber(QString);
int Check_FEC_Type(QString);
int Check_FEC_Option(QString);
int Check_FEC_Rate(QString,QString,QString);
int Check_Mod_Clock_Source(QString);
int Check_Demod_Clock_Source(QString);
int Check_Mode(QString);
int Check_depth(QString);
int Check_Dir(QString);
int Check_Filter(QString);
int Check_Output(QString);
int Check_Mute(QString);
int Check_AUPC(QString);
#endif // FUNCTION_CHECK_H
